import smtplib
import uuid
from datetime import datetime

from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart



def send_admin_alert(
    employee_id,
    file_name,
    risk_level,
    detected_data,
    sender_email,
    receiver_email,
    file_content,
    action="BLOCKED"
):

    admin_email = "varunkumarguntireddi@gmail.com"

    system_email = "varunkumarguntireddi@gmail.com"

    password = "qkyqslnhmhxomove"


    # Generate unique alert ID

    alert_id = str(uuid.uuid4())[:8]

    # Current time

    alert_time = datetime.now().strftime(
        "%Y-%m-%d %H:%M:%S"
    )

    # File preview

    preview = file_content[:1000]



    subject = (
        f"🚨 DLP SECURITY ALERT | "
        f"{risk_level} | Alert ID:{alert_id}"
    )



    body = f"""
================================================
        🔐 AI POWERED DLP SECURITY SYSTEM
================================================
Dear Security Administrator,

Greetings from the Data Leakage Prevention System.

You have received a new security alert generated by
the AI-powered DLP monitoring engine.

This alert requires your attention and review.

Alert Summary:

⚠️ Risk Level:
{risk_level}

🕒 Generated Time:
{alert_time}

🆔 Alert ID:
{alert_id}

================================================
EMPLOYEE INFORMATION
================================================

Employee ID:
{employee_id}

Sender Email:
{sender_email}

================================================
FILE INFORMATION
================================================

File Name:
{file_name}

Risk Level:
{risk_level}

Security Action:
{action}

================================================
DESTINATION INFORMATION
================================================

Receiver Email:
{receiver_email}

================================================
SENSITIVE DATA DETECTED
================================================

{detected_data}

================================================
FILE CONTENT PREVIEW
================================================

{preview}

================================================
SECURITY RECOMMENDATION
================================================

"""


    if risk_level == "CRITICAL":

        body += """

🚨 CRITICAL ALERT

Immediate investigation is required.

The file transfer has been blocked automatically.

Recommended actions:

• Review employee activity logs.
• Verify data access permissions.
• Investigate possible data leakage attempt.
• Take necessary security actions.

"""


    elif risk_level == "HIGH":

        body += """

⚠️ HIGH RISK ALERT

Please verify this data transfer request.

Recommended actions:

• Check employee authorization.
• Review detected sensitive information.
• Confirm whether the transfer is legitimate.

"""


    else:

        body += """

✅ LOW RISK ALERT

A low-risk activity has been detected.

Continue monitoring the system activity.

"""



    body += """

================================================

Thank you for monitoring enterprise security.

Stay vigilant and keep organizational data protected.


Regards,

AI Powered DLP Security System

================================================

"""



    msg = MIMEMultipart()


    msg["Subject"] = subject

    msg["From"] = system_email

    msg["To"] = admin_email



    msg.attach(
        MIMEText(body, "plain")
    )



    try:

        server = smtplib.SMTP(
            "smtp.gmail.com",
            587
        )


        server.starttls()


        server.login(
            system_email,
            password
        )


        server.send_message(msg)


        server.quit()


        print(
            "✅ DLP Admin Alert Sent Successfully"
        )


    except Exception as e:

        print(
            "❌ Email Sending Failed:",
            e
        )